kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
<<<<<<< HEAD
nodes:
- role: control-plane
=======
name: dev
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /myfile
    containerPath: /myfile
>>>>>>> 4c8a48c (first commit)
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 8080
    hostPort: 8080
- role: worker
<<<<<<< HEAD
- role: worker
=======
  extraMounts:
  - hostPath: /myfile
    containerPath: /myfile
- role: worker
  extraMounts:
  - hostPath: /myfile
    containerPath: /myfile
>>>>>>> 4c8a48c (first commit)
